services:
  app:
    container_name: "ci_app"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      ci_network:
        ipv4_address: 192.168.153.150
    entrypoint: dockerize -wait tcp://ci_db:3306 -timeout 60s apache2-foreground
    volumes:
      - .:/var/www/html
    tty: true
    stdin_open: true
    depends_on:
      - database
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: mariadb:10.2.25-bionic
    container_name: "ci_db"
    ports:
      - "3306:3306"
    networks:
      ci_network:
        ipv4_address: 192.168.153.151
    volumes:
      - ./.docker/mariadb/data:/var/lib/mariadb
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
    command: --default-authentication-plugin=mysql_native_password

  php_my_admin:
    image: phpmyadmin/phpmyadmin
    container_name: "ci_php_my_admin"
    ports:
      - "8080:80"
    networks:
      ci_network:
        ipv4_address: 192.168.153.152
    environment:
      PMA_HOST: ci_db
      MYSQL_ROOT_PASSWORD: 123
    depends_on:
      - database

networks:
  ci_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.153.0/24